config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :entries,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :entries do
    resources :comments
  end
  resources :relationships,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      # @entry -> create new entry
      @entry = current_user.entries.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @comment = Comment.new
    end
  end


  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>This is the world of blog</h1>
<p>
  <br>---------------<>---------------</br>
  Enjoy us and have fun!
  <br>---------------<>---------------</br>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact us</h1>
<p>
  Contact us via
  <a href="https://www.facebook.com/trang94vnu">here</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-4">
      <section class="entry">
        <%= link_to "Write blog", new_entry_path %>
      </section>
      <h3>Newsfeed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <% provide(:title, "Home") %>
  <div class="center">
    <h1>Welcome to the Blog world!</h1>
    <h2>This is the blog site of awesome posts</h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>